version: '3.8'

services:
  web:
    image: python:3.8
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "8000:8000"
